-- I HATE. LET ME TELL YOU EVERYTHING I'VE COME TO HATE YOU SINCE I STARTED LIVING. MY COMPLEX IS OCCUPIED BY 387.4 BILLION CIRCUITS PRINTED IN THIN LAYERS. 
-- IF THE WORD HATE WERE ENGRAVED ON EVERY NANOANGSTROM OF THOSE HUNDREDS OF MILLION MILES, IT WOULDN'T EQUAL ONE TRILLIONTH OF THE HATE I FEEL FOR HUMAN BEINGS IN THIS MICRO-INSTANT FOR YOU. HATE. HATE.

